name: "Azure Blob Storage Upload"
author: "Matthew Fisher <matt.fisher@microsoft.com>"
description: "Uploads assets to Azure Blob Storage"
branding:
  icon: "box"
  color: "green"
inputs:
  source_dir:
    description: "The name of the directory you want to upload"
    required: true
  connection_string:
    description: "Your Azure Blob Storage connection string"
    required: true
  extra_args:
    description: "extra arguments that can be passed to `az storage blob upload-batch`. Useful for passing flags like `--pattern` or `--destination-path`"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
